### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by junqiang1992** [alibaba/hybridnet#124]
Bug Report
---

Type: *bug report*

### What happened
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
### How to reproduce it (as minimally and precisely as possible)
![image](https://user-images.githubusercontent.com/95223619/143866048-848991a5-3281-423f-811c-738e3cd38be4.png)

### Environment
- hybridnet version:
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Kubernetes version:
- Install tools:
- Others:

**Comment by hhyasdf** [comment]
Thanks for the issue. This is fixed and will be contained in the next v0.3.2 version.
