### ISSUE TITLE
Not sure what they want to do. IPVLAN or MACVLAN

### ISSUE THREAD

**Issue by BurlyLuo** [alibaba/hybridnet#262]
Bug Report
---
https://github.com/cilium/cilium/pull/14436
this is based on IPVLAN. but from this repo, it's based on MACVLAN. not sure what they want to do. 
Type: *bug report*

### Environment
- hybridnet version:
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Kubernetes version:
- Install tools:
- Others:

**Comment by hhyasdf** [comment]
Sorry I just don't understander your words, what do you mean exactly?

**Comment by chestack** [comment]
https://github.com/cilium/cilium/pull/14436 is for how to use terway(ipvlan) as first cni plugin and integrate cilium to leverage ebpf progs to support k8s svc and network policy functions.

IMO hybridnet is for different scenarios, by the way where is MACVLAN related info in hybridnet that I did not find.
