### ISSUE TITLE
Just for learnning from Calico?

### ISSUE THREAD

**Issue by BurlyLuo** [alibaba/hybridnet#263]
Bug Report
---

Type: *bug report*

### Environment
- hybridnet version:
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Kubernetes version:
- Install tools:
- Others:

**Comment by hhyasdf** [comment]
That's ridiculous.

**Comment by BurlyLuo** [comment]
Repeated production wheels
